nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Smart lock
            description: ~
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/company(?!/doc) # Accepts routes under /api except /api/doc
