nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: Smart lock
            description: ~
            version: 1.0.0
    areas:
        path_patterns:
            - ^/company(?!/doc)
