security:
    encoders:
        App\Entity\Company:
            algorithm: bcrypt

    providers:
        entity_provider:
            entity:
                class: App\Entity\Company
                property: email

    firewalls:
        company_login:
            pattern:  ^/company/login
            methods: [POST]
            stateless: true
            anonymous: true
            json_login:
                check_path: /company/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        company_register:
            pattern:  ^/company
            methods: [POST]
            stateless: true
            anonymous: true

        api:
            pattern:  ^/
            stateless: true
            anonymous: false
            provider: entity_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/company/login, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/company, methods: [POST], roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }