parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Trait,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\EventListener\AuthenticationSuccessListener:
        tags:
            - { name: kernel.event_subscriber }

    App\EventListener\JWTCreatedListener:
        tags:
            - { name: kernel.event_subscriber }
